import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    appName:'PlantWise',
    myGarden:'My Garden', addPlant:'+ Add Plant', searchPlants:'Search your plants...',
    daysGrowing:'days growing', startByAdding:'Start by adding your first plant',
    youreGrowing:"You're growing", plants:'plants', plant:'plant',
    gardenEmpty:'Your garden is empty',
    gardenEmptyDesc:'Identify a plant by name or photo and get a complete AI-powered care guide.',
    addFirstPlant:'+ Add your first plant', noMatch:'No plants match your search or filters.',
    clearAll:'Clear all', clearFilters:'✕ Clear filters', signOut:'Sign out',
    garden:'Garden', settings:'Settings', loadingGarden:'Loading your garden...',
    deletePlant:'Delete this plant?',
    deleteDesc:'This will permanently delete the plant and all its chat history, journal entries, and care guide.',
    cancel:'Cancel', delete:'Delete', waterLog:'💧 Water', watered:'✓ Watered!',
    all:'All', beginner:'Beginner', intermediate:'Intermediate', expert:'Expert',
    indoor:'Indoor', outdoor:'Outdoor',
    careGuide:'Care Guide', askAI:'Ask AI', journal:'Journal', back:'Back',
    generatingCare:'Generating care guide...',
    regenerateIn:'Regenerate in', regenPrompt:'Regenerate it in',
    careGuideInEnglish:'Care guide may still be in English.',
    soil:'Soil', watering:'Watering', sunlight:'Sunlight', temperature:'Temperature',
    fertilizer:'Fertilizer', potting:'Potting', pruning:'Pruning', problems:'Problems',
    pests:'Pests', timeline:'Timeline', propagation:'Propagation', toxicity:'Toxicity',
    companions:'Companion Plants',
    thinking:'Thinking...', askPlaceholder:'Ask about your',
    suggYellow:'Why are my leaves turning yellow?', suggRepot:'When should I repot?',
    suggWater:'How much water does it need?', suggLight:'Is it getting enough light?',
    logToday:'Log Today', addPhoto:'Add photo', saveEntry:'Save Entry',
    noEntries:'No entries yet. Start logging your plant journey!',
    journalPlaceholder:"What's happening with your plant today?",
    addPlantTitle:'Add a Plant', identifyPlantStep:'Identify Plant',
    confirmPlantStep:'Confirm Plant', settingUp:'Setting Up...',
    howToIdentify:'How would you like to identify your plant?',
    byName:'By Name', byNameDesc:'Type the plant name',
    byPhoto:'By Photo', byPhotoDesc:'Upload a plant photo',
    enterPlantName:'Enter the plant name as you know it',
    plantNamePlaceholder:'e.g. Monstera, Tulsi, Money Plant...',
    uploadPhoto:'Upload a clear photo of the plant',
    clickToSelect:'Click to select photo',
    identifyingPlant:'Identifying...', identifyBtn:'Identify Plant →',
    isThisCorrect:'Is this the correct plant?',
    orDidYouMean:'Or did you mean?', tryAgain:'← Try again',
    addToGarden:'✓ Add to Garden', addingPlant:'Adding plant to your garden...',
    generatingAI:'Generating AI care guide...',
    generatingAINote:'Generating complete care guide with AI...',
    couldNotIdentify:'Could not identify this plant. Please try again.',
    pleaseEnterName:'Please enter a plant name',
    pleaseSelectImage:'Please select an image',
    profileInfo:'Profile Info', changePassword:'Change Password',
    manageNotifications:'Notifications', deleteAccountLabel:'Delete Account',
    profileInfoSub:'Update your display name', changePasswordSub:'Update your password',
    notificationsSub:'Manage reminders', deleteAccountSub:'Permanently remove your data',
    displayName:'Display Name', yourName:'Your name',
    emailAddress:'Email Address', emailCannotChange:'Email cannot be changed',
    saveChanges:'Save Changes', newPassword:'New Password', minChars:'Min. 6 characters',
    confirmNewPassword:'Confirm New Password', repeatPassword:'Repeat new password',
    updatePassword:'Update Password',
    chooseReminders:"Choose which reminders you'd like to receive.",
    wateringReminders:'💧 Watering reminders', wateringRemindersSub:'Get notified when plants need water',
    fertilizingReminders:'🌿 Fertilizing reminders', fertilizingRemindersSub:'Get notified when plants need feeding',
    repottingReminders:'🪴 Repotting reminders', repottingRemindersSub:'Get notified when plants need repotting',
    savePreferences:'Save Preferences',
    typeDeleteToConfirm:'Type DELETE to confirm', cannotBeUndone:'This cannot be undone',
    deleteWarning:'All your plants, care guides, chat history, and journal entries will be permanently deleted.',
    deleteAccountBtn:'🗑️ Permanently Delete Account',
    profileUpdated:'✓ Profile updated successfully',
    passwordChanged:'✓ Password changed successfully',
    notifSaved:'✓ Notification preferences saved',
    passwordMismatch:'✗ Passwords do not match',
    passwordShort:'✗ Password must be at least 6 characters',
    welcomeBack:'Welcome back', startGrowing:'Start growing',
    signInToGarden:'Sign in to your garden', createFreeAccount:'Create your free account',
    emailPlaceholder:'Email address', passwordPlaceholder:'Password',
    signIn:'Sign In', createAccount:'Create Account',
    continueWithGoogle:'Continue with Google',
    dontHaveAccount:"Don't have an account? ", alreadyHaveAccount:'Already have an account? ',
    signUpFree:'Sign up free',
    tagline:'Grow smarter,\nnot harder.',
    featureIdentify:'AI-powered plant identification', featureGuides:'Complete care guides',
    featureChat:'Persistent follow-up chat', featureJournal:'Growth journal & reminders',
    accountCreated:'Account created! Please check your email to confirm.',
    reminders:'Reminders', markAllRead:'Mark all read', allCaughtUp:'All caught up!',
    generating:'Generating...',
    // Care guide field labels
    fType:'Type', fPH:'pH', fMix:'Mix', fTips:'Tips', fFrequency:'Frequency',
    fAmount:'Amount', fMethod:'Method', fOverwatering:'Overwatering', fUnderwatering:'Underwatering',
    fRequirement:'Requirement', fHoursDay:'Hours/day', fIndoorPlacement:'Indoor placement',
    fIdealRange:'Ideal range', fMinimum:'Minimum', fMaximum:'Maximum', fHumidity:'Humidity',
    fFrostTolerant:'Frost tolerant', fSeason:'Season', fOrganic:'Organic option',
    fPotSize:'Pot size', fMaterial:'Material', fRepotting:'Repotting freq.', fSigns:'Signs',
    fNeeded:'Needed', fIssues:'issues', fStages:'stages',
    fBestMethod:'Best method', fBestSeason:'Best season', fMethods:'Methods', fSteps:'Steps',
    fSymptoms:'Symptoms', fCause:'Cause', fSolution:'Solution', fTreatment:'Treatment',
    fToxic:'Toxic ⚠️', fNonToxic:'Non-toxic ✅', fToHumans:'To humans', fToPets:'To pets', fDetails:'Details',
    fYes:'Yes', fNo:'No',
  },
  hi: {
    appName:'PlantWise',
    myGarden:'मेरा बगीचा', addPlant:'+ पौधा जोड़ें', searchPlants:'अपने पौधे खोजें...',
    daysGrowing:'दिन से बढ़ रहा है', startByAdding:'अपना पहला पौधा जोड़कर शुरू करें',
    youreGrowing:'आप', plants:'पौधे उगा रहे हैं', plant:'पौधा',
    gardenEmpty:'आपका बगीचा खाली है',
    gardenEmptyDesc:'नाम या फोटो से पौधे की पहचान करें और पूरा AI केयर गाइड पाएं।',
    addFirstPlant:'+ पहला पौधा जोड़ें', noMatch:'कोई पौधा नहीं मिला।',
    clearAll:'सब हटाएं', clearFilters:'✕ फ़िल्टर हटाएं', signOut:'साइन आउट',
    garden:'बगीचा', settings:'सेटिंग्स', loadingGarden:'बगीचा लोड हो रहा है...',
    deletePlant:'यह पौधा हटाएं?',
    deleteDesc:'यह पौधा और उसकी सभी जानकारी हमेशा के लिए हट जाएगी।',
    cancel:'रद्द करें', delete:'हटाएं', waterLog:'💧 पानी दें', watered:'✓ पानी दिया!',
    all:'सभी', beginner:'शुरुआती', intermediate:'मध्यम', expert:'विशेषज्ञ',
    indoor:'घर के अंदर', outdoor:'बाहर',
    careGuide:'देखभाल गाइड', askAI:'AI से पूछें', journal:'जर्नल', back:'वापस',
    generatingCare:'केयर गाइड बन रहा है...',
    regenerateIn:'में पुनः बनाएं', regenPrompt:'इसे इसमें पुनः बनाएं',
    careGuideInEnglish:'केयर गाइड अभी भी अंग्रेज़ी में हो सकता है।',
    soil:'मिट्टी', watering:'पानी', sunlight:'धूप', temperature:'तापमान',
    fertilizer:'खाद', potting:'गमला', pruning:'छंटाई', problems:'समस्याएं',
    pests:'कीड़े', timeline:'समयरेखा', propagation:'प्रजनन', toxicity:'विषाक्तता',
    companions:'साथी पौधे',
    thinking:'सोच रहा हूं...', askPlaceholder:'अपने पौधे के बारे में पूछें',
    suggYellow:'पत्तियाँ पीली क्यों हो रही हैं?', suggRepot:'पौधा कब बदलें?',
    suggWater:'कितना पानी चाहिए?', suggLight:'क्या पर्याप्त रोशनी मिल रही है?',
    logToday:'आज का लॉग', addPhoto:'फोटो जोड़ें', saveEntry:'सेव करें',
    noEntries:'अभी कोई एंट्री नहीं। अपनी पौधे की यात्रा शुरू करें!',
    journalPlaceholder:'आज आपके पौधे के साथ क्या हो रहा है?',
    addPlantTitle:'पौधा जोड़ें', identifyPlantStep:'पहचान करें',
    confirmPlantStep:'पुष्टि करें', settingUp:'तैयार हो रहा है...',
    howToIdentify:'आप अपने पौधे की पहचान कैसे करना चाहते हैं?',
    byName:'नाम से', byNameDesc:'पौधे का नाम लिखें',
    byPhoto:'फोटो से', byPhotoDesc:'पौधे की फोटो अपलोड करें',
    enterPlantName:'पौधे का नाम जैसे आप जानते हैं',
    plantNamePlaceholder:'जैसे: मनीप्लांट, तुलसी, गुलाब...',
    uploadPhoto:'पौधे की साफ़ फोटो अपलोड करें',
    clickToSelect:'फोटो चुनने के लिए क्लिक करें',
    identifyingPlant:'पहचान हो रही है...', identifyBtn:'पौधा पहचानें →',
    isThisCorrect:'क्या यह सही पौधा है?',
    orDidYouMean:'या क्या आपका मतलब था?', tryAgain:'← फिर कोशिश करें',
    addToGarden:'✓ बगीचे में जोड़ें', addingPlant:'पौधा बगीचे में जोड़ा जा रहा है...',
    generatingAI:'AI केयर गाइड बन रहा है...',
    generatingAINote:'AI से पूरा केयर गाइड बन रहा है...',
    couldNotIdentify:'पौधे की पहचान नहीं हो सकी। कृपया पुनः प्रयास करें।',
    pleaseEnterName:'कृपया पौधे का नाम दर्ज करें',
    pleaseSelectImage:'कृपया एक फोटो चुनें',
    profileInfo:'प्रोफ़ाइल जानकारी', changePassword:'पासवर्ड बदलें',
    manageNotifications:'सूचनाएं', deleteAccountLabel:'अकाउंट हटाएं',
    profileInfoSub:'अपना नाम अपडेट करें', changePasswordSub:'अपना पासवर्ड बदलें',
    notificationsSub:'रिमाइंडर प्रबंधित करें', deleteAccountSub:'अपना डेटा स्थायी रूप से हटाएं',
    displayName:'नाम', yourName:'आपका नाम',
    emailAddress:'ईमेल पता', emailCannotChange:'ईमेल नहीं बदला जा सकता',
    saveChanges:'बदलाव सेव करें', newPassword:'नया पासवर्ड', minChars:'कम से कम 6 अक्षर',
    confirmNewPassword:'पासवर्ड दोबारा लिखें', repeatPassword:'नया पासवर्ड दोहराएं',
    updatePassword:'पासवर्ड अपडेट करें',
    chooseReminders:'चुनें कि आप कौन से रिमाइंडर प्राप्त करना चाहते हैं।',
    wateringReminders:'💧 पानी देने के रिमाइंडर', wateringRemindersSub:'जब पौधे को पानी की जरूरत हो',
    fertilizingReminders:'🌿 खाद देने के रिमाइंडर', fertilizingRemindersSub:'जब पौधे को खाद की जरूरत हो',
    repottingReminders:'🪴 गमला बदलने के रिमाइंडर', repottingRemindersSub:'जब पौधे को नया गमला चाहिए',
    savePreferences:'प्राथमिकताएं सेव करें',
    typeDeleteToConfirm:'पुष्टि के लिए DELETE टाइप करें', cannotBeUndone:'यह पूर्ववत नहीं किया जा सकता',
    deleteWarning:'आपके सभी पौधे, केयर गाइड, चैट और जर्नल एंट्री स्थायी रूप से हट जाएंगी।',
    deleteAccountBtn:'🗑️ अकाउंट स्थायी रूप से हटाएं',
    profileUpdated:'✓ प्रोफ़ाइल सफलतापूर्वक अपडेट हुई',
    passwordChanged:'✓ पासवर्ड सफलतापूर्वक बदला गया',
    notifSaved:'✓ सूचना प्राथमिकताएं सेव हुईं',
    passwordMismatch:'✗ पासवर्ड मेल नहीं खाते',
    passwordShort:'✗ पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
    welcomeBack:'वापस आपका स्वागत है', startGrowing:'उगाना शुरू करें',
    signInToGarden:'अपने बगीचे में लॉगिन करें', createFreeAccount:'मुफ्त अकाउंट बनाएं',
    emailPlaceholder:'ईमेल पता', passwordPlaceholder:'पासवर्ड',
    signIn:'लॉगिन करें', createAccount:'अकाउंट बनाएं',
    continueWithGoogle:'Google से जारी रखें',
    dontHaveAccount:'अकाउंट नहीं है? ', alreadyHaveAccount:'पहले से अकाउंट है? ',
    signUpFree:'मुफ्त साइन अप करें',
    tagline:'समझदारी से उगाएं,\nमेहनत कम करें।',
    featureIdentify:'AI से पौधे की पहचान', featureGuides:'पूरी देखभाल गाइड',
    featureChat:'लगातार AI चैट', featureJournal:'ग्रोथ जर्नल और रिमाइंडर',
    accountCreated:'अकाउंट बन गया! कृपया अपना ईमेल देखें।',
    reminders:'रिमाइंडर', markAllRead:'सब पढ़ा हुआ मार्क करें', allCaughtUp:'सब ठीक है!',
    generating:'बन रहा है...',
    // Care guide field labels
    fType:'प्रकार', fPH:'pH', fMix:'मिश्रण', fTips:'सुझाव', fFrequency:'आवृत्ति',
    fAmount:'मात्रा', fMethod:'तरीका', fOverwatering:'अधिक पानी के लक्षण', fUnderwatering:'कम पानी के लक्षण',
    fRequirement:'आवश्यकता', fHoursDay:'घंटे/दिन', fIndoorPlacement:'घर में स्थान',
    fIdealRange:'आदर्श रेंज', fMinimum:'न्यूनतम', fMaximum:'अधिकतम', fHumidity:'नमी',
    fFrostTolerant:'पाला सहनशीलता', fSeason:'मौसम', fOrganic:'जैविक विकल्प',
    fPotSize:'गमले का आकार', fMaterial:'सामग्री', fRepotting:'दोबारा लगाना', fSigns:'संकेत',
    fNeeded:'जरूरी है', fIssues:'समस्याएं', fStages:'चरण',
    fBestMethod:'सबसे अच्छा तरीका', fBestSeason:'सबसे अच्छा मौसम', fMethods:'तरीके', fSteps:'चरण',
    fSymptoms:'लक्षण', fCause:'कारण', fSolution:'समाधान', fTreatment:'उपचार',
    fToxic:'विषाक्त ⚠️', fNonToxic:'गैर-विषाक्त ✅', fToHumans:'मनुष्यों के लिए', fToPets:'पालतू जानवरों के लिए', fDetails:'विवरण',
    fYes:'हाँ', fNo:'नहीं',
  },
  kn: {
    appName:'PlantWise',
    myGarden:'ನನ್ನ ತೋಟ', addPlant:'+ ಗಿಡ ಸೇರಿಸಿ', searchPlants:'ನಿಮ್ಮ ಗಿಡಗಳನ್ನು ಹುಡುಕಿ...',
    daysGrowing:'ದಿನಗಳಿಂದ ಬೆಳೆಯುತ್ತಿದೆ', startByAdding:'ನಿಮ್ಮ ಮೊದಲ ಗಿಡ ಸೇರಿಸುವ ಮೂಲಕ ಪ್ರಾರಂಭಿಸಿ',
    youreGrowing:'ನೀವು', plants:'ಗಿಡಗಳನ್ನು ಬೆಳೆಸುತ್ತಿದ್ದೀರಿ', plant:'ಗಿಡ',
    gardenEmpty:'ನಿಮ್ಮ ತೋಟ ಖಾಲಿಯಾಗಿದೆ',
    gardenEmptyDesc:'ಹೆಸರು ಅಥವಾ ಫೋಟೋ ಮೂಲಕ ಗಿಡ ಗುರುತಿಸಿ ಮತ್ತು AI ಆರೈಕೆ ಮಾರ್ಗದರ್ಶಿ ಪಡೆಯಿರಿ.',
    addFirstPlant:'+ ಮೊದಲ ಗಿಡ ಸೇರಿಸಿ', noMatch:'ಯಾವುದೇ ಗಿಡ ಹೊಂದಾಣಿಕೆಯಾಗಲಿಲ್ಲ.',
    clearAll:'ಎಲ್ಲ ತೆರವು', clearFilters:'✕ ಫಿಲ್ಟರ್ ತೆರವು', signOut:'ಸೈನ್ ಔಟ್',
    garden:'ತೋಟ', settings:'ಸೆಟ್ಟಿಂಗ್ಸ್', loadingGarden:'ತೋಟ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    deletePlant:'ಈ ಗಿಡ ಅಳಿಸಬೇಕೇ?',
    deleteDesc:'ಈ ಗಿಡ ಮತ್ತು ಅದರ ಎಲ್ಲ ಮಾಹಿತಿ ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಲ್ಪಡುತ್ತದೆ.',
    cancel:'ರದ್ದು', delete:'ಅಳಿಸಿ', waterLog:'💧 ನೀರು ಹಾಕಿ', watered:'✓ ನೀರು ಹಾಕಲಾಗಿದೆ!',
    all:'ಎಲ್ಲ', beginner:'ಆರಂಭಿಕ', intermediate:'ಮಧ್ಯಮ', expert:'ತಜ್ಞ',
    indoor:'ಒಳಾಂಗಣ', outdoor:'ಹೊರಾಂಗಣ',
    careGuide:'ಆರೈಕೆ ಮಾರ್ಗದರ್ಶಿ', askAI:'AI ಕೇಳಿ', journal:'ಜರ್ನಲ್', back:'ಹಿಂದೆ',
    generatingCare:'ಆರೈಕೆ ಮಾರ್ಗದರ್ಶಿ ತಯಾರಾಗುತ್ತಿದೆ...',
    regenerateIn:'ಭಾಷೆಯಲ್ಲಿ ಮರುಸೃಷ್ಟಿ', regenPrompt:'ಇದನ್ನು ಈ ಭಾಷೆಯಲ್ಲಿ ಮರುಸೃಷ್ಟಿ ಮಾಡಿ',
    careGuideInEnglish:'ಆರೈಕೆ ಮಾರ್ಗದರ್ಶಿ ಇನ್ನೂ ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿರಬಹುದು.',
    soil:'ಮಣ್ಣು', watering:'ನೀರು', sunlight:'ಬಿಸಿಲು', temperature:'ತಾಪಮಾನ',
    fertilizer:'ಗೊಬ್ಬರ', potting:'ಕುಂಡ', pruning:'ಕತ್ತರಿಸುವಿಕೆ', problems:'ಸಮಸ್ಯೆಗಳು',
    pests:'ಕೀಟಗಳು', timeline:'ಸಮಯರೇಖೆ', propagation:'ಸಂತಾನೋತ್ಪತ್ತಿ', toxicity:'ವಿಷತ್ವ',
    companions:'ಜೊತೆ ಗಿಡಗಳು',
    thinking:'ಯೋಚಿಸುತ್ತಿದ್ದೇನೆ...', askPlaceholder:'ನಿಮ್ಮ ಗಿಡದ ಬಗ್ಗೆ ಕೇಳಿ',
    suggYellow:'ಎಲೆಗಳು ಹಳದಿ ಏಕೆ ಆಗುತ್ತಿವೆ?', suggRepot:'ಗಿಡ ಯಾವಾಗ ಬದಲಿಸಬೇಕು?',
    suggWater:'ಎಷ್ಟು ನೀರು ಬೇಕು?', suggLight:'ಸಾಕಷ್ಟು ಬೆಳಕು ಸಿಗುತ್ತಿದೆಯೇ?',
    logToday:'ಇಂದಿನ ದಾಖಲೆ', addPhoto:'ಫೋಟೋ ಸೇರಿಸಿ', saveEntry:'ಉಳಿಸಿ',
    noEntries:'ಇನ್ನೂ ದಾಖಲೆಗಳಿಲ್ಲ. ನಿಮ್ಮ ಗಿಡದ ಪ್ರಯಾಣ ಪ್ರಾರಂಭಿಸಿ!',
    journalPlaceholder:'ಇಂದು ನಿಮ್ಮ ಗಿಡದಲ್ಲಿ ಏನು ನಡೆಯುತ್ತಿದೆ?',
    addPlantTitle:'ಗಿಡ ಸೇರಿಸಿ', identifyPlantStep:'ಗುರುತಿಸಿ',
    confirmPlantStep:'ದೃಢೀಕರಿಸಿ', settingUp:'ತಯಾರಾಗುತ್ತಿದೆ...',
    howToIdentify:'ನೀವು ನಿಮ್ಮ ಗಿಡವನ್ನು ಹೇಗೆ ಗುರುತಿಸಲು ಬಯಸುತ್ತೀರಿ?',
    byName:'ಹೆಸರಿನಿಂದ', byNameDesc:'ಗಿಡದ ಹೆಸರು ಟೈಪ್ ಮಾಡಿ',
    byPhoto:'ಫೋಟೋದಿಂದ', byPhotoDesc:'ಗಿಡದ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    enterPlantName:'ನಿಮಗೆ ತಿಳಿದ ಗಿಡದ ಹೆಸರು ನಮೂದಿಸಿ',
    plantNamePlaceholder:'ಉದಾ: ತುಳಸಿ, ಗುಲಾಬಿ, ಮನಿಪ್ಲಾಂಟ್...',
    uploadPhoto:'ಗಿಡದ ಸ್ಪಷ್ಟ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    clickToSelect:'ಫೋಟೋ ಆಯ್ಕೆ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ',
    identifyingPlant:'ಗುರುತಿಸಲಾಗುತ್ತಿದೆ...', identifyBtn:'ಗಿಡ ಗುರುತಿಸಿ →',
    isThisCorrect:'ಇದು ಸರಿಯಾದ ಗಿಡವೇ?',
    orDidYouMean:'ಅಥವಾ ನೀವು ಇದನ್ನು ಅರ್ಥೈಸಿದ್ದೀರಾ?', tryAgain:'← ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    addToGarden:'✓ ತೋಟಕ್ಕೆ ಸೇರಿಸಿ', addingPlant:'ಗಿಡವನ್ನು ತೋಟಕ್ಕೆ ಸೇರಿಸಲಾಗುತ್ತಿದೆ...',
    generatingAI:'AI ಆರೈಕೆ ಮಾರ್ಗದರ್ಶಿ ತಯಾರಾಗುತ್ತಿದೆ...',
    generatingAINote:'AI ನಿಂದ ಸಂಪೂರ್ಣ ಆರೈಕೆ ಮಾರ್ಗದರ್ಶಿ ತಯಾರಾಗುತ್ತಿದೆ...',
    couldNotIdentify:'ಈ ಗಿಡವನ್ನು ಗುರುತಿಸಲಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    pleaseEnterName:'ದಯವಿಟ್ಟು ಗಿಡದ ಹೆಸರು ನಮೂದಿಸಿ',
    pleaseSelectImage:'ದಯವಿಟ್ಟು ಒಂದು ಫೋಟೋ ಆಯ್ಕೆ ಮಾಡಿ',
    profileInfo:'ಪ್ರೊಫೈಲ್ ಮಾಹಿತಿ', changePassword:'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಿಸಿ',
    manageNotifications:'ಸೂಚನೆಗಳು', deleteAccountLabel:'ಅಕೌಂಟ್ ಅಳಿಸಿ',
    profileInfoSub:'ನಿಮ್ಮ ಹೆಸರು ಅಪ್‌ಡೇಟ್ ಮಾಡಿ', changePasswordSub:'ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ಬದಲಿಸಿ',
    notificationsSub:'ರಿಮೈಂಡರ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ', deleteAccountSub:'ನಿಮ್ಮ ಡೇಟಾ ಶಾಶ್ವತವಾಗಿ ತೆಗೆದುಹಾಕಿ',
    displayName:'ಹೆಸರು', yourName:'ನಿಮ್ಮ ಹೆಸರು',
    emailAddress:'ಇಮೇಲ್ ವಿಳಾಸ', emailCannotChange:'ಇಮೇಲ್ ಬದಲಿಸಲಾಗುವುದಿಲ್ಲ',
    saveChanges:'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ', newPassword:'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್', minChars:'ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳು',
    confirmNewPassword:'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ', repeatPassword:'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್ ಪುನರಾವರ್ತಿಸಿ',
    updatePassword:'ಪಾಸ್‌ವರ್ಡ್ ಅಪ್‌ಡೇಟ್ ಮಾಡಿ',
    chooseReminders:'ನೀವು ಯಾವ ರಿಮೈಂಡರ್‌ಗಳನ್ನು ಪಡೆಯಲು ಬಯಸುತ್ತೀರಿ ಎಂಬುದನ್ನು ಆಯ್ಕೆ ಮಾಡಿ.',
    wateringReminders:'💧 ನೀರು ಹಾಕುವ ರಿಮೈಂಡರ್', wateringRemindersSub:'ಗಿಡಕ್ಕೆ ನೀರು ಬೇಕಾದಾಗ ಸೂಚನೆ',
    fertilizingReminders:'🌿 ಗೊಬ್ಬರ ಹಾಕುವ ರಿಮೈಂಡರ್', fertilizingRemindersSub:'ಗಿಡಕ್ಕೆ ಆಹಾರ ಬೇಕಾದಾಗ ಸೂಚನೆ',
    repottingReminders:'🪴 ಕುಂಡ ಬದಲಿಸುವ ರಿಮೈಂಡರ್', repottingRemindersSub:'ಗಿಡಕ್ಕೆ ಹೊಸ ಕುಂಡ ಬೇಕಾದಾಗ ಸೂಚನೆ',
    savePreferences:'ಆದ್ಯತೆಗಳನ್ನು ಉಳಿಸಿ',
    typeDeleteToConfirm:'ದೃಢೀಕರಿಸಲು DELETE ಟೈಪ್ ಮಾಡಿ', cannotBeUndone:'ಇದನ್ನು ರದ್ದು ಮಾಡಲಾಗುವುದಿಲ್ಲ',
    deleteWarning:'ನಿಮ್ಮ ಎಲ್ಲ ಗಿಡಗಳು, ಆರೈಕೆ ಮಾರ್ಗದರ್ಶಿಗಳು, ಚಾಟ್ ಮತ್ತು ಜರ್ನಲ್ ನಮೂದುಗಳು ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಲ್ಪಡುತ್ತವೆ.',
    deleteAccountBtn:'🗑️ ಅಕೌಂಟ್ ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಿ',
    profileUpdated:'✓ ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ಅಪ್‌ಡೇಟ್ ಆಗಿದೆ',
    passwordChanged:'✓ ಪಾಸ್‌ವರ್ಡ್ ಯಶಸ್ವಿಯಾಗಿ ಬದಲಾಯಿಸಲಾಗಿದೆ',
    notifSaved:'✓ ಸೂಚನಾ ಆದ್ಯತೆಗಳನ್ನು ಉಳಿಸಲಾಗಿದೆ',
    passwordMismatch:'✗ ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಾಣಿಕೆಯಾಗುತ್ತಿಲ್ಲ',
    passwordShort:'✗ ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳಾಗಿರಬೇಕು',
    welcomeBack:'ಮತ್ತೆ ಸ್ವಾಗತ', startGrowing:'ಬೆಳೆಯಲು ಪ್ರಾರಂಭಿಸಿ',
    signInToGarden:'ನಿಮ್ಮ ತೋಟಕ್ಕೆ ಲಾಗಿನ್ ಮಾಡಿ', createFreeAccount:'ಉಚಿತ ಅಕೌಂಟ್ ರಚಿಸಿ',
    emailPlaceholder:'ಇಮೇಲ್ ವಿಳಾಸ', passwordPlaceholder:'ಪಾಸ್‌ವರ್ಡ್',
    signIn:'ಲಾಗಿನ್', createAccount:'ಅಕೌಂಟ್ ರಚಿಸಿ',
    continueWithGoogle:'Google ನಿಂದ ಮುಂದುವರಿಸಿ',
    dontHaveAccount:'ಅಕೌಂಟ್ ಇಲ್ಲವೇ? ', alreadyHaveAccount:'ಈಗಾಗಲೇ ಅಕೌಂಟ್ ಇದೆಯೇ? ',
    signUpFree:'ಉಚಿತ ಸೈನ್ ಅಪ್',
    tagline:'ಬುದ್ಧಿವಂತಿಕೆಯಿಂದ ಬೆಳೆಯಿರಿ,\nಕಷ್ಟ ಕಡಿಮೆ ಮಾಡಿ.',
    featureIdentify:'AI ನಿಂದ ಗಿಡ ಗುರುತಿಸುವಿಕೆ', featureGuides:'ಸಂಪೂರ್ಣ ಆರೈಕೆ ಮಾರ್ಗದರ್ಶಿ',
    featureChat:'ನಿರಂತರ AI ಚಾಟ್', featureJournal:'ಬೆಳವಣಿಗೆ ಜರ್ನಲ್ ಮತ್ತು ರಿಮೈಂಡರ್',
    accountCreated:'ಅಕೌಂಟ್ ರಚಿಸಲಾಗಿದೆ! ದಯವಿಟ್ಟು ನಿಮ್ಮ ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ.',
    reminders:'ರಿಮೈಂಡರ್‌ಗಳು', markAllRead:'ಎಲ್ಲ ಓದಿದ್ದಾಗಿ ಗುರುತಿಸಿ', allCaughtUp:'ಎಲ್ಲ ಸರಿಯಾಗಿದೆ!',
    generating:'ತಯಾರಾಗುತ್ತಿದೆ...',
    // Care guide field labels
    fType:'ಪ್ರಕಾರ', fPH:'pH', fMix:'ಮಿಶ್ರಣ', fTips:'ಸಲಹೆ', fFrequency:'ಆವರ್ತನ',
    fAmount:'ಪ್ರಮಾಣ', fMethod:'ವಿಧಾನ', fOverwatering:'ಹೆಚ್ಚು ನೀರಿನ ಲಕ್ಷಣ', fUnderwatering:'ಕಡಿಮೆ ನೀರಿನ ಲಕ್ಷಣ',
    fRequirement:'ಅಗತ್ಯತೆ', fHoursDay:'ಗಂಟೆ/ದಿನ', fIndoorPlacement:'ಒಳಗಿನ ಸ್ಥಳ',
    fIdealRange:'ಆದರ್ಶ ವ್ಯಾಪ್ತಿ', fMinimum:'ಕನಿಷ್ಠ', fMaximum:'ಗರಿಷ್ಠ', fHumidity:'ತೇವಾಂಶ',
    fFrostTolerant:'ಮಂಜು ಸಹಿಷ್ಣುತೆ', fSeason:'ಋತು', fOrganic:'ಸಾವಯವ ಆಯ್ಕೆ',
    fPotSize:'ಕುಂಡದ ಗಾತ್ರ', fMaterial:'ವಸ್ತು', fRepotting:'ಮರು ನೆಡುವಿಕೆ', fSigns:'ಚಿಹ್ನೆಗಳು',
    fNeeded:'ಅಗತ್ಯವಿದೆ', fIssues:'ಸಮಸ್ಯೆಗಳು', fStages:'ಹಂತಗಳು',
    fBestMethod:'ಅತ್ಯುತ್ತಮ ವಿಧಾನ', fBestSeason:'ಅತ್ಯುತ್ತಮ ಋತು', fMethods:'ವಿಧಾನಗಳು', fSteps:'ಹಂತಗಳು',
    fSymptoms:'ಲಕ್ಷಣಗಳು', fCause:'ಕಾರಣ', fSolution:'ಪರಿಹಾರ', fTreatment:'ಚಿಕಿತ್ಸೆ',
    fToxic:'ವಿಷಕಾರಿ ⚠️', fNonToxic:'ವಿಷರಹಿತ ✅', fToHumans:'ಮಾನವರಿಗೆ', fToPets:'ಸಾಕುಪ್ರಾಣಿಗಳಿಗೆ', fDetails:'ವಿವರಗಳು',
    fYes:'ಹೌದು', fNo:'ಇಲ್ಲ',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('pw_lang') || 'en');
  function switchLang(l) { setLang(l); localStorage.setItem('pw_lang', l); }
  const t = translations[lang] || translations.en;
  return (
    <LanguageContext.Provider value={{ lang, switchLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() { return useContext(LanguageContext); }
