import { createContext, useContext, useState, useCallback } from 'react';

const translations = {
  en: {
    appName:'PlantWise',
    myGarden:'My Garden', addPlant:'+ Add Plant', searchPlants:'Search your plants...',
    daysGrowing:'days growing', startByAdding:'Start by adding your first plant',
    youreGrowing:"You're growing", plants:'plants', plant:'plant',
    gardenEmpty:'Your garden is empty',
    gardenEmptyDesc:'Identify a plant by name or photo and get a complete AI-powered care guide.',
    addFirstPlant:'+ Add your first plant', noMatch:'No plants match your search or filters.',
    clearAll:'Clear all', clearFilters:'✕ Clear filters', signOut:'Sign out',
    garden:'Garden', settings:'Settings', loadingGarden:'Loading your garden...',
    deletePlant:'Delete this plant?',
    deleteDesc:'This will permanently delete the plant and all its chat history, journal entries, and care guide.',
    cancel:'Cancel', delete:'Delete', waterLog:'💧 Water', watered:'✓ Watered!',
    all:'All', beginner:'Beginner', intermediate:'Intermediate', expert:'Expert',
    indoor:'Indoor', outdoor:'Outdoor',
    careGuide:'Care Guide', askAI:'Ask AI', journal:'Journal', back:'Back',
    generatingCare:'Generating care guide...',
    regenerateIn:'Regenerate in', regenPrompt:'Regenerate it in',
    careGuideInEnglish:'Care guide may still be in English.',
    soil:'Soil', watering:'Watering', sunlight:'Sunlight', temperature:'Temperature',
    fertilizer:'Fertilizer', potting:'Potting', pruning:'Pruning', problems:'Problems',
    pests:'Pests', timeline:'Timeline', propagation:'Propagation', toxicity:'Toxicity',
    companions:'Companion Plants',
    thinking:'Thinking...', askPlaceholder:'Ask about your',
    suggYellow:'Why are my leaves turning yellow?', suggRepot:'When should I repot?',
    suggWater:'How much water does it need?', suggLight:'Is it getting enough light?',
    logToday:'Log Today', addPhoto:'Add photo', saveEntry:'Save Entry',
    noEntries:'No entries yet. Start logging your plant journey!',
    journalPlaceholder:"What's happening with your plant today?",
    addPlantTitle:'Add a Plant', identifyPlantStep:'Identify Plant',
    confirmPlantStep:'Confirm Plant', settingUp:'Setting Up...',
    howToIdentify:'How would you like to identify your plant?',
    byName:'By Name', byNameDesc:'Type the plant name',
    byPhoto:'By Photo', byPhotoDesc:'Upload a plant photo',
    enterPlantName:'Enter the plant name as you know it',
    plantNamePlaceholder:'e.g. Monstera, Tulsi, Money Plant...',
    uploadPhoto:'Upload a clear photo of the plant',
    clickToSelect:'Click to select photo',
    identifyingPlant:'Identifying...', identifyBtn:'Identify Plant →',
    isThisCorrect:'Is this the correct plant?',
    orDidYouMean:'Or did you mean?', tryAgain:'← Try again',
    addToGarden:'✓ Add to Garden', addingPlant:'Adding plant to your garden...',
    generatingAI:'Generating AI care guide...',
    generatingAINote:'Generating complete care guide with AI...',
    couldNotIdentify:'Could not identify this plant. Please try again.',
    pleaseEnterName:'Please enter a plant name',
    pleaseSelectImage:'Please select an image',
    profileInfo:'Profile Info', changePassword:'Change Password',
    manageNotifications:'Notifications', deleteAccountLabel:'Delete Account',
    profileInfoSub:'Update your display name', changePasswordSub:'Update your password',
    notificationsSub:'Manage reminders', deleteAccountSub:'Permanently remove your data',
    displayName:'Display Name', yourName:'Your name',
    emailAddress:'Email Address', emailCannotChange:'Email cannot be changed',
    saveChanges:'Save Changes', newPassword:'New Password', minChars:'Min. 6 characters',
    confirmNewPassword:'Confirm New Password', repeatPassword:'Repeat new password',
    updatePassword:'Update Password',
    chooseReminders:"Choose which reminders you'd like to receive.",
    wateringReminders:'💧 Watering reminders', wateringRemindersSub:'Get notified when plants need water',
    fertilizingReminders:'🌿 Fertilizing reminders', fertilizingRemindersSub:'Get notified when plants need feeding',
    repottingReminders:'🪴 Repotting reminders', repottingRemindersSub:'Get notified when plants need repotting',
    savePreferences:'Save Preferences',
    typeDeleteToConfirm:'Type DELETE to confirm', cannotBeUndone:'This cannot be undone',
    deleteWarning:'All your plants, care guides, chat history, and journal entries will be permanently deleted.',
    deleteAccountBtn:'🗑️ Permanently Delete Account',
    profileUpdated:'✓ Profile updated successfully',
    passwordChanged:'✓ Password changed successfully',
    notifSaved:'✓ Notification preferences saved',
    passwordMismatch:'✗ Passwords do not match',
    passwordShort:'✗ Password must be at least 6 characters',
    welcomeBack:'Welcome back', startGrowing:'Start growing',
    signInToGarden:'Sign in to your garden', createFreeAccount:'Create your free account',
    emailPlaceholder:'Email address', passwordPlaceholder:'Password',
    signIn:'Sign In', createAccount:'Create Account',
    continueWithGoogle:'Continue with Google',
    dontHaveAccount:"Don't have an account? ", alreadyHaveAccount:'Already have an account? ',
    signUpFree:'Sign up free',
    tagline:'Grow smarter,\nnot harder.',
    featureIdentify:'AI-powered plant identification', featureGuides:'Complete care guides',
    featureChat:'Persistent follow-up chat', featureJournal:'Growth journal & reminders',
    accountCreated:'Account created! Please check your email to confirm.',
    reminders:'Reminders', markAllRead:'Mark all read', allCaughtUp:'All caught up!',
    generating:'Generating...',
    // Care guide field labels
    fType:'Type', fPH:'pH', fMix:'Mix', fTips:'Tips', fFrequency:'Frequency',
    fAmount:'Amount', fMethod:'Method', fOverwatering:'Overwatering', fUnderwatering:'Underwatering',
    fRequirement:'Requirement', fHoursDay:'Hours/day', fIndoorPlacement:'Indoor placement',
    fIdealRange:'Ideal range', fMinimum:'Minimum', fMaximum:'Maximum', fHumidity:'Humidity',
    fFrostTolerant:'Frost tolerant', fSeason:'Season', fOrganic:'Organic option',
    fPotSize:'Pot size', fMaterial:'Material', fRepotting:'Repotting freq.', fSigns:'Signs',
    fNeeded:'Needed', fIssues:'issues', fStages:'stages',
    fBestMethod:'Best method', fBestSeason:'Best season', fMethods:'Methods', fSteps:'Steps',
    fSymptoms:'Symptoms', fCause:'Cause', fSolution:'Solution', fTreatment:'Treatment',
    fToxic:'Toxic ⚠️', fNonToxic:'Non-toxic ✅', fToHumans:'To humans', fToPets:'To pets', fDetails:'Details',
    fYes:'Yes', fNo:'No',
    // Dashboard new sections
    plantTips:'🌿 Plant Tips', tapToReveal:'Tap to reveal', tapToLearn:'Tap to learn more →',
    plantFacts:'🌍 Plant Facts', factOf:'of',
    growingTips:'📚 Growing Tips', tapToExpand:'Tap to expand',
    healthLabel:'Health', gardenHealth:'Garden Health',
    // Season tips
    springName:'Spring', summerName:'Summer', autumnName:'Autumn', winterName:'Winter',
    springTip:'Start fertilizing again! Repot root-bound plants. Great time to propagate.',
    summerTip:'Water more frequently. Watch for pests. Protect from harsh afternoon sun.',
    autumnTip:'Slow down fertilizing. Bring outdoor plants inside before frost.',
    winterTip:'Reduce watering frequency. Most plants are dormant. Keep away from cold windows.',
    seasonCareTip:'Care Tip',
    // Tip cards
    tipWateringTitle:'Watering', tipWateringFront:'Proper hydration is key to plant health.',
    tipWateringBack:'Check soil moisture 1" deep before watering. Most plants prefer deep, infrequent watering over shallow daily watering.',
    tipSunlightTitle:'Sunlight', tipSunlightFront:'Light is food for your plants.',
    tipSunlightBack:'Rotate your plants 90° weekly for even growth. South-facing windows get the most light in the northern hemisphere.',
    tipTempTitle:'Temperature', tipTempFront:'Temperature swings stress plants.',
    tipTempBack:'Keep plants away from AC vents and cold drafts. Most tropicals prefer 18–27°C. Sudden drops cause leaf drop.',
    tipSoilTitle:'Soil', tipSoilFront:'Good soil = healthy roots = thriving plant.',
    tipSoilBack:'Refresh potting mix every 1–2 years. Add perlite for drainage and worm castings for slow-release nutrients.',
    tipPruningTitle:'Pruning', tipPruningFront:'Pruning encourages bushier, fuller growth.',
    tipPruningBack:'Always cut above a leaf node at 45°. Remove dead or yellowing leaves first. Clean your scissors with alcohol first.',
    tipFertTitle:'Fertilizing', tipFertFront:'Feed your plants during their growth season.',
    tipFertBack:'Use a balanced NPK fertilizer (like 10-10-10) every 2–4 weeks in spring/summer. Stop feeding in winter.',
    // Growing tips accordion
    gtPotTitle:'Choose the Right Pot', gtPotTip:'Always use pots with drainage holes. Root rot from waterlogged soil kills more plants than anything else.',
    gtLightTitle:'Light First, Water Second', gtLightTip:'Assess your light conditions before buying any plant. Even drought-tolerant plants fail without adequate light.',
    gtNewTitle:'Acclimatize New Plants', gtNewTip:"New plants need 1–2 weeks to adjust. Keep them away from other plants to watch for pests, and don't repot immediately.",
    gtSeasonTitle:'Seasonal Routine', gtSeasonTip:'Water more in summer, less in winter. Most plants rest during winter and don\'t need fertilizer from October to February.',
    gtInspectTitle:'Inspect Weekly', gtInspectTip:'Check the undersides of leaves weekly. Catching pests early (spider mites, mealybugs) prevents an infestation.',
    gtDeadTitle:'Dead-head Regularly', gtDeadTip:'Remove spent flowers and yellow leaves promptly. Dead plant material invites fungus and wastes the plant\'s energy.',
    // Plant facts
    fact1:'The world\'s oldest living tree is over 5,000 years old — a bristlecone pine in California named Methuselah.',
    fact2:'Plants can communicate with each other through underground fungal networks called the "Wood Wide Web".',
    fact3:'A single mature tree absorbs about 21 kg of CO₂ per year and produces enough oxygen for 2 people.',
    fact4:'There are over 400,000 known plant species on Earth — and scientists discover new ones every year.',
    fact5:'The Venus flytrap can snap shut in as little as 0.1 seconds — one of the fastest movements in the plant kingdom.',
    fact6:'Cacti can survive years without rain. The saguaro cactus can absorb up to 750 litres of water in a single rainstorm.',
    fact7:'Bamboo is the fastest-growing plant on Earth — some species grow up to 91 cm in a single day.',
    fact8:'Most plants grow toward light (phototropism), but roots grow away from light and toward gravity (gravitropism).',
    factTag1:'Did You Know?', factTag2:'Science', factTag3:'Environment', factTag4:'Biodiversity',
    factTag5:'Amazing', factTag6:'Survival', factTag7:'Record', factTag8:'Biology',
  },
  hi: {
    appName:'PlantWise',
    myGarden:'मेरा बगीचा', addPlant:'+ पौधा जोड़ें', searchPlants:'अपने पौधे खोजें...',
    daysGrowing:'दिन से बढ़ रहा है', startByAdding:'अपना पहला पौधा जोड़कर शुरू करें',
    youreGrowing:'आप', plants:'पौधे उगा रहे हैं', plant:'पौधा',
    gardenEmpty:'आपका बगीचा खाली है',
    gardenEmptyDesc:'नाम या फोटो से पौधे की पहचान करें और पूरा AI केयर गाइड पाएं।',
    addFirstPlant:'+ पहला पौधा जोड़ें', noMatch:'कोई पौधा नहीं मिला।',
    clearAll:'सब हटाएं', clearFilters:'✕ फ़िल्टर हटाएं', signOut:'साइन आउट',
    garden:'बगीचा', settings:'सेटिंग्स', loadingGarden:'बगीचा लोड हो रहा है...',
    deletePlant:'यह पौधा हटाएं?',
    deleteDesc:'यह पौधा और उसकी सभी जानकारी हमेशा के लिए हट जाएगी।',
    cancel:'रद्द करें', delete:'हटाएं', waterLog:'💧 पानी दें', watered:'✓ पानी दिया!',
    all:'सभी', beginner:'शुरुआती', intermediate:'मध्यम', expert:'विशेषज्ञ',
    indoor:'घर के अंदर', outdoor:'बाहर',
    careGuide:'देखभाल गाइड', askAI:'AI से पूछें', journal:'जर्नल', back:'वापस',
    generatingCare:'केयर गाइड बन रहा है...',
    regenerateIn:'में पुनः बनाएं', regenPrompt:'इसे इसमें पुनः बनाएं',
    careGuideInEnglish:'केयर गाइड अभी भी अंग्रेज़ी में हो सकता है।',
    soil:'मिट्टी', watering:'पानी', sunlight:'धूप', temperature:'तापमान',
    fertilizer:'खाद', potting:'गमला', pruning:'छंटाई', problems:'समस्याएं',
    pests:'कीड़े', timeline:'समयरेखा', propagation:'प्रजनन', toxicity:'विषाक्तता',
    companions:'साथी पौधे',
    thinking:'सोच रहा हूं...', askPlaceholder:'अपने पौधे के बारे में पूछें',
    suggYellow:'पत्तियाँ पीली क्यों हो रही हैं?', suggRepot:'पौधा कब बदलें?',
    suggWater:'कितना पानी चाहिए?', suggLight:'क्या पर्याप्त रोशनी मिल रही है?',
    logToday:'आज का लॉग', addPhoto:'फोटो जोड़ें', saveEntry:'सेव करें',
    noEntries:'अभी कोई एंट्री नहीं। अपनी पौधे की यात्रा शुरू करें!',
    journalPlaceholder:'आज आपके पौधे के साथ क्या हो रहा है?',
    addPlantTitle:'पौधा जोड़ें', identifyPlantStep:'पहचान करें',
    confirmPlantStep:'पुष्टि करें', settingUp:'तैयार हो रहा है...',
    howToIdentify:'आप अपने पौधे की पहचान कैसे करना चाहते हैं?',
    byName:'नाम से', byNameDesc:'पौधे का नाम लिखें',
    byPhoto:'फोटो से', byPhotoDesc:'पौधे की फोटो अपलोड करें',
    enterPlantName:'पौधे का नाम जैसे आप जानते हैं',
    plantNamePlaceholder:'जैसे: मनीप्लांट, तुलसी, गुलाब...',
    uploadPhoto:'पौधे की साफ़ फोटो अपलोड करें',
    clickToSelect:'फोटो चुनने के लिए क्लिक करें',
    identifyingPlant:'पहचान हो रही है...', identifyBtn:'पौधा पहचानें →',
    isThisCorrect:'क्या यह सही पौधा है?',
    orDidYouMean:'या क्या आपका मतलब था?', tryAgain:'← फिर कोशिश करें',
    addToGarden:'✓ बगीचे में जोड़ें', addingPlant:'पौधा बगीचे में जोड़ा जा रहा है...',
    generatingAI:'AI केयर गाइड बन रहा है...',
    generatingAINote:'AI से पूरा केयर गाइड बन रहा है...',
    couldNotIdentify:'पौधे की पहचान नहीं हो सकी। कृपया पुनः प्रयास करें।',
    pleaseEnterName:'कृपया पौधे का नाम दर्ज करें',
    pleaseSelectImage:'कृपया एक फोटो चुनें',
    profileInfo:'प्रोफ़ाइल जानकारी', changePassword:'पासवर्ड बदलें',
    manageNotifications:'सूचनाएं', deleteAccountLabel:'अकाउंट हटाएं',
    profileInfoSub:'अपना नाम अपडेट करें', changePasswordSub:'अपना पासवर्ड बदलें',
    notificationsSub:'रिमाइंडर प्रबंधित करें', deleteAccountSub:'अपना डेटा स्थायी रूप से हटाएं',
    displayName:'नाम', yourName:'आपका नाम',
    emailAddress:'ईमेल पता', emailCannotChange:'ईमेल नहीं बदला जा सकता',
    saveChanges:'बदलाव सेव करें', newPassword:'नया पासवर्ड', minChars:'कम से कम 6 अक्षर',
    confirmNewPassword:'पासवर्ड दोबारा लिखें', repeatPassword:'नया पासवर्ड दोहराएं',
    updatePassword:'पासवर्ड अपडेट करें',
    chooseReminders:'चुनें कि आप कौन से रिमाइंडर प्राप्त करना चाहते हैं।',
    wateringReminders:'💧 पानी देने के रिमाइंडर', wateringRemindersSub:'जब पौधे को पानी की जरूरत हो',
    fertilizingReminders:'🌿 खाद देने के रिमाइंडर', fertilizingRemindersSub:'जब पौधे को खाद की जरूरत हो',
    repottingReminders:'🪴 गमला बदलने के रिमाइंडर', repottingRemindersSub:'जब पौधे को नया गमला चाहिए',
    savePreferences:'प्राथमिकताएं सेव करें',
    typeDeleteToConfirm:'पुष्टि के लिए DELETE टाइप करें', cannotBeUndone:'यह पूर्ववत नहीं किया जा सकता',
    deleteWarning:'आपके सभी पौधे, केयर गाइड, चैट और जर्नल एंट्री स्थायी रूप से हट जाएंगी।',
    deleteAccountBtn:'🗑️ अकाउंट स्थायी रूप से हटाएं',
    profileUpdated:'✓ प्रोफ़ाइल सफलतापूर्वक अपडेट हुई',
    passwordChanged:'✓ पासवर्ड सफलतापूर्वक बदला गया',
    notifSaved:'✓ सूचना प्राथमिकताएं सेव हुईं',
    passwordMismatch:'✗ पासवर्ड मेल नहीं खाते',
    passwordShort:'✗ पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
    welcomeBack:'वापस आपका स्वागत है', startGrowing:'उगाना शुरू करें',
    signInToGarden:'अपने बगीचे में लॉगिन करें', createFreeAccount:'मुफ्त अकाउंट बनाएं',
    emailPlaceholder:'ईमेल पता', passwordPlaceholder:'पासवर्ड',
    signIn:'लॉगिन करें', createAccount:'अकाउंट बनाएं',
    continueWithGoogle:'Google से जारी रखें',
    dontHaveAccount:'अकाउंट नहीं है? ', alreadyHaveAccount:'पहले से अकाउंट है? ',
    signUpFree:'मुफ्त साइन अप करें',
    tagline:'समझदारी से उगाएं,\nमेहनत कम करें।',
    featureIdentify:'AI से पौधे की पहचान', featureGuides:'पूरी देखभाल गाइड',
    featureChat:'लगातार AI चैट', featureJournal:'ग्रोथ जर्नल और रिमाइंडर',
    accountCreated:'अकाउंट बन गया! कृपया अपना ईमेल देखें।',
    reminders:'रिमाइंडर', markAllRead:'सब पढ़ा हुआ मार्क करें', allCaughtUp:'सब ठीक है!',
    generating:'बन रहा है...',
    // Care guide field labels
    fType:'प्रकार', fPH:'pH', fMix:'मिश्रण', fTips:'सुझाव', fFrequency:'आवृत्ति',
    fAmount:'मात्रा', fMethod:'तरीका', fOverwatering:'अधिक पानी के लक्षण', fUnderwatering:'कम पानी के लक्षण',
    fRequirement:'आवश्यकता', fHoursDay:'घंटे/दिन', fIndoorPlacement:'घर में स्थान',
    fIdealRange:'आदर्श रेंज', fMinimum:'न्यूनतम', fMaximum:'अधिकतम', fHumidity:'नमी',
    fFrostTolerant:'पाला सहनशीलता', fSeason:'मौसम', fOrganic:'जैविक विकल्प',
    fPotSize:'गमले का आकार', fMaterial:'सामग्री', fRepotting:'दोबारा लगाना', fSigns:'संकेत',
    fNeeded:'जरूरी है', fIssues:'समस्याएं', fStages:'चरण',
    fBestMethod:'सबसे अच्छा तरीका', fBestSeason:'सबसे अच्छा मौसम', fMethods:'तरीके', fSteps:'चरण',
    fSymptoms:'लक्षण', fCause:'कारण', fSolution:'समाधान', fTreatment:'उपचार',
    fToxic:'विषाक्त ⚠️', fNonToxic:'गैर-विषाक्त ✅', fToHumans:'मनुष्यों के लिए', fToPets:'पालतू जानवरों के लिए', fDetails:'विवरण',
    fYes:'हाँ', fNo:'नहीं',
    // Dashboard new sections
    plantTips:'🌿 पौधों के टिप्स', tapToReveal:'टैप करें', tapToLearn:'और जानें →',
    plantFacts:'🌍 पौधों के रोचक तथ्य', factOf:'का',
    growingTips:'📚 उगाने के टिप्स', tapToExpand:'टैप करें',
    healthLabel:'स्वास्थ्य', gardenHealth:'बगीचे का स्वास्थ्य',
    springName:'वसंत', summerName:'गर्मी', autumnName:'शरद', winterName:'सर्दी',
    springTip:'फिर से खाद देना शुरू करें! जड़ों से भरे पौधों को नए गमले में लगाएं। प्रसार के लिए अच्छा समय।',
    summerTip:'अधिक बार पानी दें। कीटों पर नज़र रखें। कड़ी दोपहर की धूप से बचाएं।',
    autumnTip:'खाद देना धीमा करें। पाले से पहले बाहरी पौधों को अंदर लाएं।',
    winterTip:'पानी देना कम करें। अधिकतर पौधे सुप्त अवस्था में होते हैं। ठंडी खिड़कियों से दूर रखें।',
    seasonCareTip:'देखभाल टिप',
    tipWateringTitle:'पानी देना', tipWateringFront:'सही पानी पौधे के स्वास्थ्य की कुंजी है।',
    tipWateringBack:'पानी देने से पहले 1 इंच गहरी मिट्टी की नमी जांचें। अधिकतर पौधे गहरे, कम पानी को पसंद करते हैं।',
    tipSunlightTitle:'धूप', tipSunlightFront:'रोशनी पौधों का भोजन है।',
    tipSunlightBack:'समान विकास के लिए अपने पौधों को हर हफ्ते 90° घुमाएं। दक्षिण मुखी खिड़कियों में सबसे ज्यादा रोशनी मिलती है।',
    tipTempTitle:'तापमान', tipTempFront:'तापमान में बदलाव पौधों को तनाव देता है।',
    tipTempBack:'पौधों को AC और ठंडी हवा से दूर रखें। अधिकतर उष्णकटिबंधीय पौधे 18–27°C पसंद करते हैं।',
    tipSoilTitle:'मिट्टी', tipSoilFront:'अच्छी मिट्टी = स्वस्थ जड़ें = फलता-फूलता पौधा।',
    tipSoilBack:'हर 1–2 साल में मिट्टी बदलें। जल निकासी के लिए पर्लाइट और धीमी खाद के लिए वर्म कास्टिंग मिलाएं।',
    tipPruningTitle:'छंटाई', tipPruningFront:'छंटाई से पौधा और भी घना बनता है।',
    tipPruningBack:'हमेशा पत्ती की गांठ के ऊपर 45° पर काटें। पहले मृत या पीली पत्तियां हटाएं।',
    tipFertTitle:'खाद देना', tipFertFront:'अपने पौधों को उनके विकास के मौसम में खाद दें।',
    tipFertBack:'वसंत/गर्मियों में हर 2–4 हफ्ते में संतुलित NPK उर्वरक दें। सर्दियों में बंद कर दें।',
    gtPotTitle:'सही गमला चुनें', gtPotTip:'हमेशा जल निकासी छेद वाले गमलों का उपयोग करें। जलभराव से जड़ सड़न सबसे ज्यादा पौधों को मारती है।',
    gtLightTitle:'पहले रोशनी, फिर पानी', gtLightTip:'कोई भी पौधा खरीदने से पहले रोशनी की स्थिति का आकलन करें।',
    gtNewTitle:'नए पौधों को अनुकूलित करें', gtNewTip:'नए पौधों को समायोजित होने के लिए 1–2 सप्ताह चाहिए। कीटों के लिए अलग रखें।',
    gtSeasonTitle:'मौसमी दिनचर्या', gtSeasonTip:'गर्मियों में अधिक पानी, सर्दियों में कम। अक्टूबर से फरवरी तक खाद न दें।',
    gtInspectTitle:'साप्ताहिक जांच', gtInspectTip:'हर हफ्ते पत्तियों की निचली सतह जांचें। शुरुआती कीट नियंत्रण प्रकोप से बचाता है।',
    gtDeadTitle:'नियमित रूप से मृत फूल हटाएं', gtDeadTip:'खर्च हो चुके फूल और पीली पत्तियां तुरंत हटाएं। मृत भाग फंगस को आमंत्रित करता है।',
    fact1:'दुनिया का सबसे पुराना जीवित पेड़ 5,000 साल से अधिक पुराना है — कैलिफोर्निया में मेथुसेलह नाम का ब्रिसलकोन पाइन।',
    fact2:'पौधे "वुड वाइड वेब" नामक भूमिगत कवक नेटवर्क के माध्यम से एक दूसरे से संवाद कर सकते हैं।',
    fact3:'एक परिपक्व पेड़ सालाना लगभग 21 किग्रा CO₂ सोखता है और 2 लोगों के लिए पर्याप्त ऑक्सीजन बनाता है।',
    fact4:'पृथ्वी पर 400,000 से अधिक ज्ञात पौधों की प्रजातियां हैं — और वैज्ञानिक हर साल नई खोजते हैं।',
    fact5:'वीनस फ्लाईट्रैप 0.1 सेकंड में बंद हो सकता है — यह पौधे जगत की सबसे तेज गतिविधियों में से एक है।',
    fact6:'कैक्टस वर्षों तक बिना बारिश के जीवित रह सकते हैं। सागुआरो कैक्टस एक बारिश में 750 लीटर पानी सोख सकता है।',
    fact7:'बांस पृथ्वी पर सबसे तेज उगने वाला पौधा है — कुछ प्रजातियां एक दिन में 91 सेमी तक बढ़ती हैं।',
    fact8:'अधिकतर पौधे रोशनी की ओर बढ़ते हैं, लेकिन जड़ें रोशनी से दूर और गुरुत्वाकर्षण की ओर बढ़ती हैं।',
    factTag1:'क्या आप जानते हैं?', factTag2:'विज्ञान', factTag3:'पर्यावरण', factTag4:'जैव विविधता',
    factTag5:'अद्भुत', factTag6:'जीवित रहना', factTag7:'रिकॉर्ड', factTag8:'जीव विज्ञान',
  },
  kn: {
    appName:'PlantWise',
    myGarden:'ನನ್ನ ತೋಟ', addPlant:'+ ಗಿಡ ಸೇರಿಸಿ', searchPlants:'ನಿಮ್ಮ ಗಿಡಗಳನ್ನು ಹುಡುಕಿ...',
    daysGrowing:'ದಿನಗಳಿಂದ ಬೆಳೆಯುತ್ತಿದೆ', startByAdding:'ನಿಮ್ಮ ಮೊದಲ ಗಿಡ ಸೇರಿಸುವ ಮೂಲಕ ಪ್ರಾರಂಭಿಸಿ',
    youreGrowing:'ನೀವು', plants:'ಗಿಡಗಳನ್ನು ಬೆಳೆಸುತ್ತಿದ್ದೀರಿ', plant:'ಗಿಡ',
    gardenEmpty:'ನಿಮ್ಮ ತೋಟ ಖಾಲಿಯಾಗಿದೆ',
    gardenEmptyDesc:'ಹೆಸರು ಅಥವಾ ಫೋಟೋ ಮೂಲಕ ಗಿಡ ಗುರುತಿಸಿ ಮತ್ತು AI ಆರೈಕೆ ಮಾರ್ಗದರ್ಶಿ ಪಡೆಯಿರಿ.',
    addFirstPlant:'+ ಮೊದಲ ಗಿಡ ಸೇರಿಸಿ', noMatch:'ಯಾವುದೇ ಗಿಡ ಹೊಂದಾಣಿಕೆಯಾಗಲಿಲ್ಲ.',
    clearAll:'ಎಲ್ಲ ತೆರವು', clearFilters:'✕ ಫಿಲ್ಟರ್ ತೆರವು', signOut:'ಸೈನ್ ಔಟ್',
    garden:'ತೋಟ', settings:'ಸೆಟ್ಟಿಂಗ್ಸ್', loadingGarden:'ತೋಟ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    deletePlant:'ಈ ಗಿಡ ಅಳಿಸಬೇಕೇ?',
    deleteDesc:'ಈ ಗಿಡ ಮತ್ತು ಅದರ ಎಲ್ಲ ಮಾಹಿತಿ ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಲ್ಪಡುತ್ತದೆ.',
    cancel:'ರದ್ದು', delete:'ಅಳಿಸಿ', waterLog:'💧 ನೀರು ಹಾಕಿ', watered:'✓ ನೀರು ಹಾಕಲಾಗಿದೆ!',
    all:'ಎಲ್ಲ', beginner:'ಆರಂಭಿಕ', intermediate:'ಮಧ್ಯಮ', expert:'ತಜ್ಞ',
    indoor:'ಒಳಾಂಗಣ', outdoor:'ಹೊರಾಂಗಣ',
    careGuide:'ಆರೈಕೆ ಮಾರ್ಗದರ್ಶಿ', askAI:'AI ಕೇಳಿ', journal:'ಜರ್ನಲ್', back:'ಹಿಂದೆ',
    generatingCare:'ಆರೈಕೆ ಮಾರ್ಗದರ್ಶಿ ತಯಾರಾಗುತ್ತಿದೆ...',
    regenerateIn:'ಭಾಷೆಯಲ್ಲಿ ಮರುಸೃಷ್ಟಿ', regenPrompt:'ಇದನ್ನು ಈ ಭಾಷೆಯಲ್ಲಿ ಮರುಸೃಷ್ಟಿ ಮಾಡಿ',
    careGuideInEnglish:'ಆರೈಕೆ ಮಾರ್ಗದರ್ಶಿ ಇನ್ನೂ ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿರಬಹುದು.',
    soil:'ಮಣ್ಣು', watering:'ನೀರು', sunlight:'ಬಿಸಿಲು', temperature:'ತಾಪಮಾನ',
    fertilizer:'ಗೊಬ್ಬರ', potting:'ಕುಂಡ', pruning:'ಕತ್ತರಿಸುವಿಕೆ', problems:'ಸಮಸ್ಯೆಗಳು',
    pests:'ಕೀಟಗಳು', timeline:'ಸಮಯರೇಖೆ', propagation:'ಸಂತಾನೋತ್ಪತ್ತಿ', toxicity:'ವಿಷತ್ವ',
    companions:'ಜೊತೆ ಗಿಡಗಳು',
    thinking:'ಯೋಚಿಸುತ್ತಿದ್ದೇನೆ...', askPlaceholder:'ನಿಮ್ಮ ಗಿಡದ ಬಗ್ಗೆ ಕೇಳಿ',
    suggYellow:'ಎಲೆಗಳು ಹಳದಿ ಏಕೆ ಆಗುತ್ತಿವೆ?', suggRepot:'ಗಿಡ ಯಾವಾಗ ಬದಲಿಸಬೇಕು?',
    suggWater:'ಎಷ್ಟು ನೀರು ಬೇಕು?', suggLight:'ಸಾಕಷ್ಟು ಬೆಳಕು ಸಿಗುತ್ತಿದೆಯೇ?',
    logToday:'ಇಂದಿನ ದಾಖಲೆ', addPhoto:'ಫೋಟೋ ಸೇರಿಸಿ', saveEntry:'ಉಳಿಸಿ',
    noEntries:'ಇನ್ನೂ ದಾಖಲೆಗಳಿಲ್ಲ. ನಿಮ್ಮ ಗಿಡದ ಪ್ರಯಾಣ ಪ್ರಾರಂಭಿಸಿ!',
    journalPlaceholder:'ಇಂದು ನಿಮ್ಮ ಗಿಡದಲ್ಲಿ ಏನು ನಡೆಯುತ್ತಿದೆ?',
    addPlantTitle:'ಗಿಡ ಸೇರಿಸಿ', identifyPlantStep:'ಗುರುತಿಸಿ',
    confirmPlantStep:'ದೃಢೀಕರಿಸಿ', settingUp:'ತಯಾರಾಗುತ್ತಿದೆ...',
    howToIdentify:'ನೀವು ನಿಮ್ಮ ಗಿಡವನ್ನು ಹೇಗೆ ಗುರುತಿಸಲು ಬಯಸುತ್ತೀರಿ?',
    byName:'ಹೆಸರಿನಿಂದ', byNameDesc:'ಗಿಡದ ಹೆಸರು ಟೈಪ್ ಮಾಡಿ',
    byPhoto:'ಫೋಟೋದಿಂದ', byPhotoDesc:'ಗಿಡದ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    enterPlantName:'ನಿಮಗೆ ತಿಳಿದ ಗಿಡದ ಹೆಸರು ನಮೂದಿಸಿ',
    plantNamePlaceholder:'ಉದಾ: ತುಳಸಿ, ಗುಲಾಬಿ, ಮನಿಪ್ಲಾಂಟ್...',
    uploadPhoto:'ಗಿಡದ ಸ್ಪಷ್ಟ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    clickToSelect:'ಫೋಟೋ ಆಯ್ಕೆ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ',
    identifyingPlant:'ಗುರುತಿಸಲಾಗುತ್ತಿದೆ...', identifyBtn:'ಗಿಡ ಗುರುತಿಸಿ →',
    isThisCorrect:'ಇದು ಸರಿಯಾದ ಗಿಡವೇ?',
    orDidYouMean:'ಅಥವಾ ನೀವು ಇದನ್ನು ಅರ್ಥೈಸಿದ್ದೀರಾ?', tryAgain:'← ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    addToGarden:'✓ ತೋಟಕ್ಕೆ ಸೇರಿಸಿ', addingPlant:'ಗಿಡವನ್ನು ತೋಟಕ್ಕೆ ಸೇರಿಸಲಾಗುತ್ತಿದೆ...',
    generatingAI:'AI ಆರೈಕೆ ಮಾರ್ಗದರ್ಶಿ ತಯಾರಾಗುತ್ತಿದೆ...',
    generatingAINote:'AI ನಿಂದ ಸಂಪೂರ್ಣ ಆರೈಕೆ ಮಾರ್ಗದರ್ಶಿ ತಯಾರಾಗುತ್ತಿದೆ...',
    couldNotIdentify:'ಈ ಗಿಡವನ್ನು ಗುರುತಿಸಲಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    pleaseEnterName:'ದಯವಿಟ್ಟು ಗಿಡದ ಹೆಸರು ನಮೂದಿಸಿ',
    pleaseSelectImage:'ದಯವಿಟ್ಟು ಒಂದು ಫೋಟೋ ಆಯ್ಕೆ ಮಾಡಿ',
    profileInfo:'ಪ್ರೊಫೈಲ್ ಮಾಹಿತಿ', changePassword:'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಿಸಿ',
    manageNotifications:'ಸೂಚನೆಗಳು', deleteAccountLabel:'ಅಕೌಂಟ್ ಅಳಿಸಿ',
    profileInfoSub:'ನಿಮ್ಮ ಹೆಸರು ಅಪ್‌ಡೇಟ್ ಮಾಡಿ', changePasswordSub:'ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ಬದಲಿಸಿ',
    notificationsSub:'ರಿಮೈಂಡರ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ', deleteAccountSub:'ನಿಮ್ಮ ಡೇಟಾ ಶಾಶ್ವತವಾಗಿ ತೆಗೆದುಹಾಕಿ',
    displayName:'ಹೆಸರು', yourName:'ನಿಮ್ಮ ಹೆಸರು',
    emailAddress:'ಇಮೇಲ್ ವಿಳಾಸ', emailCannotChange:'ಇಮೇಲ್ ಬದಲಿಸಲಾಗುವುದಿಲ್ಲ',
    saveChanges:'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ', newPassword:'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್', minChars:'ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳು',
    confirmNewPassword:'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ', repeatPassword:'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್ ಪುನರಾವರ್ತಿಸಿ',
    updatePassword:'ಪಾಸ್‌ವರ್ಡ್ ಅಪ್‌ಡೇಟ್ ಮಾಡಿ',
    chooseReminders:'ನೀವು ಯಾವ ರಿಮೈಂಡರ್‌ಗಳನ್ನು ಪಡೆಯಲು ಬಯಸುತ್ತೀರಿ ಎಂಬುದನ್ನು ಆಯ್ಕೆ ಮಾಡಿ.',
    wateringReminders:'💧 ನೀರು ಹಾಕುವ ರಿಮೈಂಡರ್', wateringRemindersSub:'ಗಿಡಕ್ಕೆ ನೀರು ಬೇಕಾದಾಗ ಸೂಚನೆ',
    fertilizingReminders:'🌿 ಗೊಬ್ಬರ ಹಾಕುವ ರಿಮೈಂಡರ್', fertilizingRemindersSub:'ಗಿಡಕ್ಕೆ ಆಹಾರ ಬೇಕಾದಾಗ ಸೂಚನೆ',
    repottingReminders:'🪴 ಕುಂಡ ಬದಲಿಸುವ ರಿಮೈಂಡರ್', repottingRemindersSub:'ಗಿಡಕ್ಕೆ ಹೊಸ ಕುಂಡ ಬೇಕಾದಾಗ ಸೂಚನೆ',
    savePreferences:'ಆದ್ಯತೆಗಳನ್ನು ಉಳಿಸಿ',
    typeDeleteToConfirm:'ದೃಢೀಕರಿಸಲು DELETE ಟೈಪ್ ಮಾಡಿ', cannotBeUndone:'ಇದನ್ನು ರದ್ದು ಮಾಡಲಾಗುವುದಿಲ್ಲ',
    deleteWarning:'ನಿಮ್ಮ ಎಲ್ಲ ಗಿಡಗಳು, ಆರೈಕೆ ಮಾರ್ಗದರ್ಶಿಗಳು, ಚಾಟ್ ಮತ್ತು ಜರ್ನಲ್ ನಮೂದುಗಳು ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಲ್ಪಡುತ್ತವೆ.',
    deleteAccountBtn:'🗑️ ಅಕೌಂಟ್ ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಿ',
    profileUpdated:'✓ ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ಅಪ್‌ಡೇಟ್ ಆಗಿದೆ',
    passwordChanged:'✓ ಪಾಸ್‌ವರ್ಡ್ ಯಶಸ್ವಿಯಾಗಿ ಬದಲಾಯಿಸಲಾಗಿದೆ',
    notifSaved:'✓ ಸೂಚನಾ ಆದ್ಯತೆಗಳನ್ನು ಉಳಿಸಲಾಗಿದೆ',
    passwordMismatch:'✗ ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಾಣಿಕೆಯಾಗುತ್ತಿಲ್ಲ',
    passwordShort:'✗ ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳಾಗಿರಬೇಕು',
    welcomeBack:'ಮತ್ತೆ ಸ್ವಾಗತ', startGrowing:'ಬೆಳೆಯಲು ಪ್ರಾರಂಭಿಸಿ',
    signInToGarden:'ನಿಮ್ಮ ತೋಟಕ್ಕೆ ಲಾಗಿನ್ ಮಾಡಿ', createFreeAccount:'ಉಚಿತ ಅಕೌಂಟ್ ರಚಿಸಿ',
    emailPlaceholder:'ಇಮೇಲ್ ವಿಳಾಸ', passwordPlaceholder:'ಪಾಸ್‌ವರ್ಡ್',
    signIn:'ಲಾಗಿನ್', createAccount:'ಅಕೌಂಟ್ ರಚಿಸಿ',
    continueWithGoogle:'Google ನಿಂದ ಮುಂದುವರಿಸಿ',
    dontHaveAccount:'ಅಕೌಂಟ್ ಇಲ್ಲವೇ? ', alreadyHaveAccount:'ಈಗಾಗಲೇ ಅಕೌಂಟ್ ಇದೆಯೇ? ',
    signUpFree:'ಉಚಿತ ಸೈನ್ ಅಪ್',
    tagline:'ಬುದ್ಧಿವಂತಿಕೆಯಿಂದ ಬೆಳೆಯಿರಿ,\nಕಷ್ಟ ಕಡಿಮೆ ಮಾಡಿ.',
    featureIdentify:'AI ನಿಂದ ಗಿಡ ಗುರುತಿಸುವಿಕೆ', featureGuides:'ಸಂಪೂರ್ಣ ಆರೈಕೆ ಮಾರ್ಗದರ್ಶಿ',
    featureChat:'ನಿರಂತರ AI ಚಾಟ್', featureJournal:'ಬೆಳವಣಿಗೆ ಜರ್ನಲ್ ಮತ್ತು ರಿಮೈಂಡರ್',
    accountCreated:'ಅಕೌಂಟ್ ರಚಿಸಲಾಗಿದೆ! ದಯವಿಟ್ಟು ನಿಮ್ಮ ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ.',
    reminders:'ರಿಮೈಂಡರ್‌ಗಳು', markAllRead:'ಎಲ್ಲ ಓದಿದ್ದಾಗಿ ಗುರುತಿಸಿ', allCaughtUp:'ಎಲ್ಲ ಸರಿಯಾಗಿದೆ!',
    generating:'ತಯಾರಾಗುತ್ತಿದೆ...',
    // Care guide field labels
    fType:'ಪ್ರಕಾರ', fPH:'pH', fMix:'ಮಿಶ್ರಣ', fTips:'ಸಲಹೆ', fFrequency:'ಆವರ್ತನ',
    fAmount:'ಪ್ರಮಾಣ', fMethod:'ವಿಧಾನ', fOverwatering:'ಹೆಚ್ಚು ನೀರಿನ ಲಕ್ಷಣ', fUnderwatering:'ಕಡಿಮೆ ನೀರಿನ ಲಕ್ಷಣ',
    fRequirement:'ಅಗತ್ಯತೆ', fHoursDay:'ಗಂಟೆ/ದಿನ', fIndoorPlacement:'ಒಳಗಿನ ಸ್ಥಳ',
    fIdealRange:'ಆದರ್ಶ ವ್ಯಾಪ್ತಿ', fMinimum:'ಕನಿಷ್ಠ', fMaximum:'ಗರಿಷ್ಠ', fHumidity:'ತೇವಾಂಶ',
    fFrostTolerant:'ಮಂಜು ಸಹಿಷ್ಣುತೆ', fSeason:'ಋತು', fOrganic:'ಸಾವಯವ ಆಯ್ಕೆ',
    fPotSize:'ಕುಂಡದ ಗಾತ್ರ', fMaterial:'ವಸ್ತು', fRepotting:'ಮರು ನೆಡುವಿಕೆ', fSigns:'ಚಿಹ್ನೆಗಳು',
    fNeeded:'ಅಗತ್ಯವಿದೆ', fIssues:'ಸಮಸ್ಯೆಗಳು', fStages:'ಹಂತಗಳು',
    fBestMethod:'ಅತ್ಯುತ್ತಮ ವಿಧಾನ', fBestSeason:'ಅತ್ಯುತ್ತಮ ಋತು', fMethods:'ವಿಧಾನಗಳು', fSteps:'ಹಂತಗಳು',
    fSymptoms:'ಲಕ್ಷಣಗಳು', fCause:'ಕಾರಣ', fSolution:'ಪರಿಹಾರ', fTreatment:'ಚಿಕಿತ್ಸೆ',
    fToxic:'ವಿಷಕಾರಿ ⚠️', fNonToxic:'ವಿಷರಹಿತ ✅', fToHumans:'ಮಾನವರಿಗೆ', fToPets:'ಸಾಕುಪ್ರಾಣಿಗಳಿಗೆ', fDetails:'ವಿವರಗಳು',
    fYes:'ಹೌದು', fNo:'ಇಲ್ಲ',
    // Dashboard new sections
    plantTips:'🌿 ಗಿಡದ ಸಲಹೆಗಳು', tapToReveal:'ತಟ್ಟಿ ನೋಡಿ', tapToLearn:'ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ →',
    plantFacts:'🌍 ಗಿಡದ ಆಸಕ್ತಿಕರ ಸಂಗತಿಗಳು', factOf:'ರಲ್ಲಿ',
    growingTips:'📚 ಬೆಳೆಸುವ ಸಲಹೆಗಳು', tapToExpand:'ತಟ್ಟಿ ತೆರೆಯಿರಿ',
    healthLabel:'ಆರೋಗ್ಯ', gardenHealth:'ತೋಟದ ಆರೋಗ್ಯ',
    springName:'ವಸಂತ', summerName:'ಬೇಸಿಗೆ', autumnName:'ಶರದ್', winterName:'ಚಳಿಗಾಲ',
    springTip:'ಮತ್ತೆ ಗೊಬ್ಬರ ಹಾಕಲು ಪ್ರಾರಂಭಿಸಿ! ಬೇರು ತುಂಬಿದ ಗಿಡಗಳನ್ನು ಹೊಸ ಕುಂಡಕ್ಕೆ ಸ್ಥಳಾಂತರಿಸಿ.',
    summerTip:'ಹೆಚ್ಚಾಗಿ ನೀರು ಹಾಕಿ. ಕೀಟಗಳ ಮೇಲೆ ನಿಗಾ ಇರಲಿ. ಮಧ್ಯಾಹ್ನದ ಕಡುಬಿಸಿಲಿನಿಂದ ರಕ್ಷಿಸಿ.',
    autumnTip:'ಗೊಬ್ಬರ ಹಾಕುವುದನ್ನು ನಿಧಾನಿಸಿ. ಮಂಜು ಬರುವ ಮೊದಲು ಹೊರಗಿನ ಗಿಡಗಳನ್ನು ಒಳಗೆ ತನ್ನಿ.',
    winterTip:'ನೀರು ಹಾಕುವುದನ್ನು ಕಡಿಮೆ ಮಾಡಿ. ಹೆಚ್ಚಿನ ಗಿಡಗಳು ಸುಪ್ತಾವಸ್ಥೆಯಲ್ಲಿರುತ್ತವೆ. ತಣ್ಣನೆಯ ಕಿಟಕಿಗಳಿಂದ ದೂರ ಇರಿಸಿ.',
    seasonCareTip:'ಆರೈಕೆ ಸಲಹೆ',
    tipWateringTitle:'ನೀರು ಹಾಕುವಿಕೆ', tipWateringFront:'ಸರಿಯಾದ ನೀರು ಗಿಡದ ಆರೋಗ್ಯದ ಕೀಲಿ.',
    tipWateringBack:'ನೀರು ಹಾಕುವ ಮೊದಲು 1 ಇಂಚು ಆಳದ ಮಣ್ಣಿನ ತೇವಾಂಶ ಪರೀಕ್ಷಿಸಿ. ಆಳವಾಗಿ, ಕಡಿಮೆ ಬಾರಿ ನೀರು ನೀಡಿ.',
    tipSunlightTitle:'ಬಿಸಿಲು', tipSunlightFront:'ಬೆಳಕು ಗಿಡಗಳ ಆಹಾರ.',
    tipSunlightBack:'ಸಮಾನ ಬೆಳವಣಿಗೆಗೆ ಪ್ರತಿ ವಾರ ಗಿಡಗಳನ್ನು 90° ತಿರುಗಿಸಿ. ದಕ್ಷಿಣ ಮುಖದ ಕಿಟಕಿಗಳಲ್ಲಿ ಹೆಚ್ಚು ಬೆಳಕು ಸಿಗುತ್ತದೆ.',
    tipTempTitle:'ತಾಪಮಾನ', tipTempFront:'ತಾಪಮಾನದ ಏರಿಳಿತ ಗಿಡಗಳಿಗೆ ಒತ್ತಡ ಉಂಟು ಮಾಡುತ್ತದೆ.',
    tipTempBack:'ಗಿಡಗಳನ್ನು AC ಮತ್ತು ತಣ್ಣನೆಯ ಗಾಳಿಯಿಂದ ದೂರ ಇರಿಸಿ. ಹೆಚ್ಚಿನ ಉಷ್ಣವಲಯದ ಗಿಡಗಳು 18–27°C ಇಷ್ಟಪಡುತ್ತವೆ.',
    tipSoilTitle:'ಮಣ್ಣು', tipSoilFront:'ಒಳ್ಳೆಯ ಮಣ್ಣು = ಆರೋಗ್ಯಕರ ಬೇರುಗಳು = ಚೆನ್ನಾಗಿ ಬೆಳೆಯುವ ಗಿಡ.',
    tipSoilBack:'ಪ್ರತಿ 1–2 ವರ್ಷಗಳಿಗೊಮ್ಮೆ ಮಡಿಕೆ ಮಿಶ್ರಣ ಬದಲಾಯಿಸಿ. ನಿಧಾನ ಪೋಷಣೆಗಾಗಿ ಪರ್ಲೈಟ್ ಮತ್ತು ವರ್ಮ್ ಕಾಸ್ಟಿಂಗ್ ಸೇರಿಸಿ.',
    tipPruningTitle:'ಕತ್ತರಿಸುವಿಕೆ', tipPruningFront:'ಕತ್ತರಿಸುವಿಕೆ ಗಿಡವನ್ನು ದಟ್ಟಗೊಳಿಸುತ್ತದೆ.',
    tipPruningBack:'ಯಾವಾಗಲೂ ಎಲೆ ಗಂಟಿನ ಮೇಲೆ 45° ಕೋನದಲ್ಲಿ ಕತ್ತರಿಸಿ. ಮೊದಲು ಒಣಗಿದ ಎಲೆಗಳನ್ನು ತೆಗೆಯಿರಿ.',
    tipFertTitle:'ಗೊಬ್ಬರ ಹಾಕುವಿಕೆ', tipFertFront:'ಬೆಳವಣಿಗೆ ಋತುವಿನಲ್ಲಿ ಗಿಡಗಳಿಗೆ ಆಹಾರ ನೀಡಿ.',
    tipFertBack:'ವಸಂತ/ಬೇಸಿಗೆಯಲ್ಲಿ ಪ್ರತಿ 2–4 ವಾರಕ್ಕೊಮ್ಮೆ NPK ಗೊಬ್ಬರ ನೀಡಿ. ಚಳಿಗಾಲದಲ್ಲಿ ನಿಲ್ಲಿಸಿ.',
    gtPotTitle:'ಸರಿಯಾದ ಕುಂಡ ಆಯ್ಕೆ ಮಾಡಿ', gtPotTip:'ಯಾವಾಗಲೂ ನೀರು ಹರಿಯುವ ರಂಧ್ರಗಳಿರುವ ಕುಂಡ ಬಳಸಿ. ನೀರು ನಿಲ್ಲುವುದರಿಂದ ಬೇರು ಕೊಳೆಯುತ್ತದೆ.',
    gtLightTitle:'ಮೊದಲು ಬೆಳಕು, ನಂತರ ನೀರು', gtLightTip:'ಯಾವ ಗಿಡ ತರುವ ಮೊದಲೂ ಬೆಳಕಿನ ಸ್ಥಿತಿ ಅಳೆಯಿರಿ.',
    gtNewTitle:'ಹೊಸ ಗಿಡಗಳನ್ನು ಅಳವಡಿಸಿ', gtNewTip:'ಹೊಸ ಗಿಡಗಳಿಗೆ ಒಗ್ಗಿಕೊಳ್ಳಲು 1–2 ವಾರ ಬೇಕು. ಕೀಟಗಳಿಗಾಗಿ ಪ್ರತ್ಯೇಕ ಇರಿಸಿ.',
    gtSeasonTitle:'ಋತುಮಾನದ ದಿನಚರಿ', gtSeasonTip:'ಬೇಸಿಗೆಯಲ್ಲಿ ಹೆಚ್ಚು ನೀರು, ಚಳಿಗಾಲದಲ್ಲಿ ಕಡಿಮೆ. ಅಕ್ಟೋಬರ್–ಫೆಬ್ರವರಿ ಗೊಬ್ಬರ ಬೇಡ.',
    gtInspectTitle:'ವಾರಕ್ಕೊಮ್ಮೆ ಪರೀಕ್ಷಿಸಿ', gtInspectTip:'ಪ್ರತಿ ವಾರ ಎಲೆಗಳ ಕೆಳಭಾಗ ನೋಡಿ. ಆರಂಭದಲ್ಲೇ ಕೀಟ ನಿಯಂತ್ರಿಸಿದರೆ ಉಪದ್ರವ ತಡೆಯಬಹುದು.',
    gtDeadTitle:'ಒಣಗಿದ ಹೂಗಳನ್ನು ತೆಗೆಯಿರಿ', gtDeadTip:'ಹಳೆ ಹೂ ಮತ್ತು ಹಳದಿ ಎಲೆಗಳನ್ನು ತಕ್ಷಣ ತೆಗೆಯಿರಿ. ಸತ್ತ ಭಾಗ ಶಿಲೀಂಧ್ರ ಆಮಂತ್ರಿಸುತ್ತದೆ.',
    fact1:'ಜಗತ್ತಿನ ಅತ್ಯಂತ ಹಳೆಯ ಜೀವಂತ ಮರ 5,000 ವರ್ಷಕ್ಕೂ ಹಳೆಯದು — ಕ್ಯಾಲಿಫೋರ್ನಿಯಾದ ಮೆಥುಸೆಲಾ ಎಂಬ ಬ್ರಿಸ್ಟಲ್ ಕೋನ್ ಪೈನ್.',
    fact2:'ಗಿಡಗಳು "ವುಡ್ ವೈಡ್ ವೆಬ್" ಎಂಬ ಭೂಗತ ಶಿಲೀಂಧ್ರ ಜಾಲದ ಮೂಲಕ ಪರಸ್ಪರ ಸಂವಹಿಸಬಲ್ಲವು.',
    fact3:'ಒಂದು ಪ್ರಬುದ್ಧ ಮರ ವಾರ್ಷಿಕ 21 ಕಿಗ್ರಾ CO₂ ಹೀರುತ್ತದೆ ಮತ್ತು 2 ಜನರಿಗೆ ಸಾಕಾಗುವ ಆಮ್ಲಜನಕ ಉತ್ಪಾದಿಸುತ್ತದೆ.',
    fact4:'ಭೂಮಿಯ ಮೇಲೆ 400,000ಕ್ಕೂ ಹೆಚ್ಚು ತಿಳಿದ ಗಿಡ ಪ್ರಭೇದಗಳಿವೆ — ಪ್ರತಿ ವರ್ಷ ವಿಜ್ಞಾನಿಗಳು ಹೊಸದನ್ನು ಕಂಡುಹಿಡಿಯುತ್ತಾರೆ.',
    fact5:'ವೀನಸ್ ಫ್ಲೈಟ್ರ್ಯಾಪ್ 0.1 ಸೆಕೆಂಡಿನಲ್ಲಿ ಮುಚ್ಚಬಲ್ಲದು — ಇದು ಗಿಡ ಸಾಮ್ರಾಜ್ಯದ ಅತಿ ವೇಗದ ಚಲನೆಗಳಲ್ಲಿ ಒಂದು.',
    fact6:'ಕ್ಯಾಕ್ಟಸ್ ವರ್ಷಗಳ ಕಾಲ ಮಳೆ ಇಲ್ಲದೆ ಬದುಕಬಲ್ಲದು. ಸಾಗ್ವಾರೋ ಒಂದೇ ಮಳೆಯಲ್ಲಿ 750 ಲೀಟರ್ ನೀರು ಹೀರಬಲ್ಲದು.',
    fact7:'ಬಿದಿರು ಭೂಮಿಯ ಅತ್ಯಂತ ವೇಗವಾಗಿ ಬೆಳೆಯುವ ಗಿಡ — ಕೆಲವು ಜಾತಿಗಳು ಒಂದೇ ದಿನದಲ್ಲಿ 91 ಸೆಂ.ಮೀ ಬೆಳೆಯುತ್ತವೆ.',
    fact8:'ಹೆಚ್ಚಿನ ಗಿಡಗಳು ಬೆಳಕಿನ ಕಡೆ ಬೆಳೆಯುತ್ತವೆ, ಆದರೆ ಬೇರುಗಳು ಬೆಳಕಿನಿಂದ ದೂರ ಮತ್ತು ಗುರುತ್ವದ ಕಡೆ ಬೆಳೆಯುತ್ತವೆ.',
    factTag1:'ನಿಮಗೆ ಗೊತ್ತೇ?', factTag2:'ವಿಜ್ಞಾನ', factTag3:'ಪರಿಸರ', factTag4:'ಜೀವ ವೈವಿಧ್ಯ',
    factTag5:'ಅದ್ಭುತ', factTag6:'ಬದುಕುಳಿಯುವಿಕೆ', factTag7:'ದಾಖಲೆ', factTag8:'ಜೀವಶಾಸ್ತ್ರ',
  }
};

const LanguageContext = createContext();
const API_URL = process.env.REACT_APP_API_URL || 'http://localhost:5000/api';

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('pw_lang') || 'en');
  // nameCache: { 'hi': { 'Sunflower': 'सूरजमुखी', ... }, 'kn': { ... } }
  const [nameCache, setNameCache] = useState({});
  const [translatingNames, setTranslatingNames] = useState(false);

  const t = translations[lang] || translations.en;

  function switchLang(l) {
    setLang(l);
    localStorage.setItem('pw_lang', l);
    // No need to clear cache — each lang has its own key
    // tn() always checks current lang key, en returns original name
  }

  // Call this from Dashboard after plants are loaded, whenever lang changes
  // Uses currentLang param to avoid stale closure bug
  const translateNames = useCallback(async (englishNames) => {
    const currentLang = lang; // capture current lang at call time
    if (currentLang === 'en') return; // English = use original names, no translation needed
    if (!englishNames?.length) return;

    // Filter names not yet cached for current lang
    const cached = nameCache[currentLang] || {};
    const missing = englishNames.filter(n => !cached[n]);
    if (!missing.length) return;

    setTranslatingNames(true);
    try {
      const res = await fetch(`${API_URL}/plants/translate-names`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ names: missing, lang: currentLang })
      });
      const data = await res.json();
      if (data.success) {
        setNameCache(prev => ({
          ...prev,
          [currentLang]: { ...(prev[currentLang] || {}), ...data.data }
        }));
      }
    } catch(e) {
      console.error('Name translation failed:', e);
    } finally {
      setTranslatingNames(false);
    }
  }, [lang, nameCache]);

  // Translate a single name — always returns original English name when lang==='en'
  function tn(englishName) {
    if (!englishName) return englishName;
    if (lang === 'en') return englishName; // Always show English when EN is selected
    return (nameCache[lang] || {})[englishName] || englishName;
  }

  return (
    <LanguageContext.Provider value={{ lang, switchLang, t, tn, translateNames, translatingNames }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() { return useContext(LanguageContext); }
